### ISSUE TITLE
BiomeTweaker and GeographiCraft do not work with this mod and BOP.

### ISSUE THREAD

**Issue by MagmaSlime123** [juraj-hrivnak/RTGUnofficial#11]
If I'm being dumb again, then I'm sorry.

##### Affected Mod Versions:
BOP 7.0.1.2445.

- Forge version: 2860.
- RTGU version: 1.0.2.

##### Issue Description:
BOP biomes cease to generate. I am using a script file that was provided in #9. GeographiCraft also doesn't function.

##### Steps to reproduce the issue: (If it's easily reproducible.)
Use this mod with BOP and BiomeTweaker or GeographiCraft, (if BT is installed) and add the script file linked in #9 to BiomeTweaker's scripts folder.

![image](https://user-images.githubusercontent.com/51277766/223289309-64e40036-566c-422d-8ad1-9fb1daac3332.png)

No other mods are in use.

![image](https://user-images.githubusercontent.com/51277766/223289403-0fd19e2c-b68b-455f-a65e-d63bed114e6c.png)
![image](https://user-images.githubusercontent.com/51277766/223291201-c87a6b9e-fcdb-4db8-a64d-3f9e5d1eeeab.png)

##### Extra Information:
N/A. Make a Discord so I can report issues like this more easily.

**Comment by juraj-hrivnak** [comment]
Send me the latest log, please

**Comment by MagmaSlime123** [comment]
Apparently the script file HAS to be named RTG. If its named anything else and not defined in the BiomeTweaker config (it being in the scripts folder doesn't even get detected by BiomeTweaker, so that folder shouldn't exist), then it straight up doesn't work.

ProjectVibrentJourneys seems to be the only mod that has proper built-in support though, and it works without any scripts.
