### ISSUE TITLE
Better Chinese translation

### ISSUE THREAD

**Issue by krzj** [juraj-hrivnak/RTGUnofficial#16]
https://github.com/kgs233/RTG-zh_cn

**Comment by GBLodb** [comment]
https://github.com/kgs233/RTG-zh_cn/blob/main/zh_cn.lang#L299-L319

wdym by "better"?

**Comment by krzj** [comment]
> 

Ours is just eight rows.

**Comment by krzj** [comment]
https://github.com/juraj-hrivnak/RTGUnofficial/blob/d378c719b6313f23c0ed16eb0a8b56efb91e44d9/src/main/resources/assets/rtg/lang/zh_cn.lang

**Comment by juraj-hrivnak** [comment]
Added in v1.1.0
