### ISSUE TITLE
[Question] How to work with Biomes O' Plenty

### ISSUE THREAD

**Issue by tier940** [juraj-hrivnak/RTGUnofficial#18]
##### Affected Mod Versions:

- Forge version: 14.23.5.2860
- RTGU version: 1.1.0
- Biomes O' Plenty version: 1.12.2-7.0.1.2445

##### Issue Description:

We assumed that the trees and biomes in Biomes O' Plenty would be generated using RTG, but we could not confirm the generation by flying around creatively.
I also tried changing the cfg settings, but could not find any settings that had any particular effect.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. install mods
2. generate world

##### Extra Information:

- Install RoughlyEnoughIDs(version 2.0.6) and regenerate world -> not generated

**Comment by juraj-hrivnak** [comment]
This is currently possible only with BiomeTweaker, GeographiCraft or Dimensional Control.
For example, you can take a look at [Underdog's BiomeTweaker configuration](https://github.com/juraj-hrivnak/Underdog/blob/main/config/BiomeTweaker/scripts/biomes.cfg).

**Comment by tier940** [comment]
Thanks, I'll give it a try!
I will write the credit in the modpack I am creating when I apply it, using it as a reference.
