### ISSUE TITLE
BiomeTweaker refuses to allow certain Biomes O Plenty biomes to generate.

### ISSUE THREAD

**Issue by MagmaSlime123** [juraj-hrivnak/RTGUnofficial#5]
##### Affected Mod Versions:
I've tried this within a personal modpack I'm making, and I've also tried with no other mods besides BOP, BT and RTG. Same issue with or without other mods.

- Forge version: 2860.
- RTG version: 6.1.0.0-snapshot.3
- Config: https://www.dropbox.com/s/tlj2w5nb4jk5xvd/BiomeTweaker.zip?dl=0
No changes were made. This was the default config I was given.

##### Issue Description:
Title. Certain Biomes O Plenty biomes refuse to generate if using BiomeTweaker and RTG.

##### Steps to reproduce the issue: (If it's easily reproducible.)
Install RTG, Biomes O Plenty, and BiomeTweaker. Start the game, create a world, and fly around. Notice that Coral Reefs, Kelp Forests, and probably other random BOP biomes aren't generating.

##### Extra Information:
N/A. No logs/errors related to this occur, but I will provide it anyway, despite them being utterly useless.
https://pastebin.com/58Td42XJ

**Comment by juraj-hrivnak** [comment]
Your script folder is empty.

**Comment by juraj-hrivnak** [comment]
You need to add the biomes using a BiomeTweaker script

**Comment by MagmaSlime123** [comment]
No clue how scripts work. BiomeTweaker should know what mods are being used.
