### ISSUE TITLE
River generation still has some issues 

### ISSUE THREAD

**Issue by MagmaSlime123** [juraj-hrivnak/RTGUnofficial#6]
##### Affected Mod Versions:
- Forge version: 2860.
- RTG version: 6.1.0.0-snapshot.3
- BiomeTweaker version: 3.2.369.
Config: https://www.dropbox.com/s/tlj2w5nb4jk5xvd/BiomeTweaker.zip?dl=0
No changes were made. This was the default config I was given.

##### Issue Description:
Title. Rivers are very bugged.

![image](https://user-images.githubusercontent.com/51277766/187044317-6fa3d2db-989e-4867-bac5-6114e353c5b8.png)

![2022-08-27_12 44 20](https://user-images.githubusercontent.com/51277766/187044173-676d71e0-d35a-4c3f-8b92-20b8a5208bbf.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)
Install this with BiomeTweaker, create a world, and find a river.

##### Extra Information:
N/A.

**Comment by MagmaSlime123** [comment]
If the title was mean, sorry.

**Comment by juraj-hrivnak** [comment]
When using RTG alongside BiomeTweaker, you must remove the river biome to generate correctly.
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.12-master/etc/biometweaker/RTG/RTG.cfg#L246-L249
