### ISSUE TITLE
RTGU Will spawn BOP biom?

### ISSUE THREAD

**Issue by Lonelyxiya** [juraj-hrivnak/RTGUnofficial#9]
As shown in the title.

**Comment by Lonelyxiya** [comment]
The official version of RTG requires Climate Control/Geographicraft to be installed in order to spawn BOP biom. So will RTGU product BOP biom without installing Climate Control/Geographicraft?

**Comment by juraj-hrivnak** [comment]
Yes, you need either Climate Control/Geographicraft or BiomeTweaker.
See https://github.com/Team-RTG/Realistic-Terrain-Generation/wiki/BiomeTweaker-configuration

**Comment by Lonelyxiya** [comment]
Can that future version directly spawn BOP biom?

**Comment by juraj-hrivnak** [comment]
I don’t know what you mean by the future version, but this probably won’t change in the future. You need and will need Climate Control/Geographicraft or BiomeTweaker to get it to work.

**Comment by Lonelyxiya** [comment]
Because I am from mainland China, the machine translation is Deepl,so the terminology quality is not too good. But how do you say, so only through Control/Geographicraft or BiomeTweaker to spawn BOP biom?

**Comment by juraj-hrivnak** [comment]
Yes, exactly.
Install the BiomeTweaker mod and place the `biomes.cfg` in the /config/BiomeTweaker/scripts folder.
Here is the script: [biomes.zip](https://github.com/juraj-hrivnak/RTGUnofficial/files/10892238/biomes.zip)

**Comment by Lonelyxiya** [comment]
oh thanks you

**Comment by MagmaSlime123** [comment]
ProjectVibrentJourneys seems to be the only mod that has proper built-in support. I and others shouldn't have to manually write scripts to do this for other biome mods.

Probably why RTG/RTGU doesn't have many downloads.

Also, that script file doesn't even function, despite being in the folder.
